### ISSUE TITLE
问个rxjava问题

### ISSUE THREAD

**Issue by slz17** [hegaojian/WanAndroid#11]
override fun getBannList(): Observable<ApiResponse<MutableList<BannerResponse>>> {
        return Observable.just(mRepositoryManager
                .obtainRetrofitService(Api::class.java)
                .getBanner())
                .flatMap { apiResponseObservable ->
                    apiResponseObservable
                }
    }
为什么不是
mRepositoryManager
                .obtainRetrofitService(Api::class.java)
                .getBanner()
包一层再展开有特殊效果吗？

**Comment by hegaojian** [comment]
刚开始编写这个项目请求网络的时候想支持缓存的，后面出现了一个暂时无法解决的bug，就把这个写法一直遗留下来了，写到后面的请求时没注意偷懒一直Ctrl+C V，导致全部都是这样了， 这是一个问题，虽然不会出错，但是很容易误导别人，感谢老哥你的细心阅读代码，抽空我去给他改掉:joy::joy::joy:
