### ISSUE TITLE
请问使用MVPArms该如何兼容androidx

### ISSUE THREAD

**Issue by fubd** [hegaojian/WanAndroid#12]
Migrate to AndroidX 貌似无效哦

**Comment by hegaojian** [comment]
在 gradle.properties 文件中加入
android.useAndroidX=true
android.enableJetifier=true
就可以了

**Comment by hegaojian** [comment]
可以看MVPArms作者关于androidX的文章 https://mp.weixin.qq.com/s/XeJQrwbxKk6JbBn8C3fqKg

**Comment by fubd** [comment]
![image](https://user-images.githubusercontent.com/29155847/70843966-5ee08200-1e75-11ea-8ddb-fdc7b198f087.png)
加入了似乎也没效果

**Comment by hegaojian** [comment]
你这里要换成AndroidX相关的包名才行：
import androidx.fragment.app.Fragment
import androidx.fragment.app.FragmentManager
app模块中你应该要删除所有support包替换成AndroidX包

**Comment by fubd** [comment]
@hegaojian 搞定 十分感谢~

**Comment by hegaojian** [comment]
~不客气
