### ISSUE TITLE
兄弟可以弄个QQ群大家一起讨论一起进步啊

### ISSUE THREAD

**Issue by Leo78ing** [hegaojian/WanAndroid#4]

**Comment by hegaojian** [comment]
1.0.6版本个人中心有个加入我们，会添加一个玩安卓QQ群，里面都是一些大佬，可以进来一起学习

**Comment by Leo78ing** [comment]
项目死活跑不起来，编译都通不过==

**Comment by hegaojian** [comment]
看下错误提示

**Comment by Leo78ing** [comment]
你用的gradle是5.4.1，我改成我现在用的4.1了，然后报：
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.1.0] AndroidManifest.xml:24:18-86
  	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-139:19 to override.

**Comment by hegaojian** [comment]
建议把gradle版本升级一下
如果不行话参考：https://blog.csdn.net/zxwd2015/article/details/86651216
