### ISSUE TITLE
你们clone下来都可以运行？我的一直找不到相关类 之前是java开发的

### ISSUE THREAD

**Issue by qq171161636** [hegaojian/WanAndroid#6]

**Comment by hegaojian** [comment]
你的as版本与gradle版本是多少


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by qq171161636** [comment]
> 你的as版本与gradle版本是多少
> 
> ：octocat： [从gitme Android](http://flutterchina.club/app/gm.html)

**Comment by qq171161636** [comment]
> > 你的as版本与gradle版本是多少
> > ：octocat： [从gitme Android](http://flutterchina.club/app/gm.html)

第一次学习kotlin项目，昨天搞了半下午，今天搞了一上午才跑起来。kotlin的版本和gradle版本好像要对应，升级到5.4的gradle就好了。kotlin的插件版本也要和AS里的一样。感谢作者开源哈

**Comment by hegaojian** [comment]
哈哈，你弄好了就行
